---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.3.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

####################### Optimised Model to Operate Sobol Simulations for PARASOL_LCA model #########################


THIS IS NOT A FINAL VERSION. THIS IS THE START OF AN OPTIMIZED MODEL THAT WAS INTERRUPTED TO FOCUS ON FINALIZING THE ORIGINAL PARASOL_LCA MODEL WHICH CONSTITUTES AND ESSENTIAL STEP BEFORE THE OPTIMIZATION. 
IT SHOULD BE NOTED THAT THE WORK SHOULD BE CONTINUED BY THE FUTURE CANDIDATE. THIS IS WHY I PREPARED A STEP-BY-STEP GUIDE ON WHICH WE RELIED TO DEVELOP THIS MODEL.


This Notebook represents the Optimised Version on which the future candidate will be working to run Sobol. Benoît GSCHWIND and Scarlett TANNOUS proposed and worked together to establish the methodology and choose the Brightway2's functions to elaborate this work. It is not completed. However, it is in progress which means that 
the work has started with the first components which can also serve as straightforward examples on which the candidate can rely to continue the work similarly. It is indispensable to accompany this Notebook with the Original PARASOL_LCA Parameterized model that Scarlett TANNOUS and Romain BESSEAU have developped.


# Loading Libraries and Databases


This section is similar to the first few lines of the original PARASOL_LCA model. It includes the loading of Libraries and Databases that will be used in the project.

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import brightway2 as bw
from scipy.interpolate import InterpolatedUnivariateSpline
plt.style.use('ggplot')
# %matplotlib auto
```

```{python}
from bw2data.parameters import ActivityParameter, DatabaseParameter, ProjectParameter, Group
from SALib.sample import saltelli
from SALib.analyze import sobol
```

```{python}
bw.projects.current
```

```{python}
bw.projects.set_current('incer_acv')
```

```{python code_folding=c("2")}
#bw.databases
#bw.bw2setup()
'''
fpei34 =  r'C:\Users\Scarlett Tannous\MPT_Python_code\Brightway_Training\Brightway&Python\ecoinvent 3.4_cutoff_ecoSpold02_COPYSOB\datasets'
if 'ecoinvent 3.4 cutoff' in bw.databases:
    print("Database has already been imported")
else:
    ei34 = bw.SingleOutputEcospold2Importer(fpei34, 'ecoinvent 3.4 cut off')
    ei34.apply_strategies()
    ei34.statistics()
'''
#ei34.write_database()
```

```{python}
eidb = bw.Database('ecoinvent 3.4 cut off')
bio3 = bw.Database('biosphere3')
```

```{python}
len(bio3)
```

```{python}
len(eidb)
```

```{python code_folding=c("1")}
'''
if 'incer-acv' in [x[0] for x in bw.projects.report()]:
    bw.projects.delete_project('incer-acv')
    bw.projects.purge_deleted_directories
'''
```

# Print Functions


This section includes different functions allowing to display datasets with different level of details. 

```{python}
def print_data(act):
    df = pd.DataFrame(index = ['amount','unit','key','type'])
    for (i,exc) in enumerate(act.exchanges()):
        df[str(bw.get_activity(exc.input.key))] = [exc.amount, exc.unit, exc.input.key,exc['type']]
    return df.T
```

```{python}
def print_data2(act):
    df = pd.DataFrame(index = ['amount','unit'])
    for (i,exc) in enumerate(act.exchanges()):
        df[str(bw.get_activity(exc.input.key))] = [exc.amount, exc.unit]
    return df.T
```

```{python}
def print_data3(act):
    print(act)
    df = pd.DataFrame(index = ['amount','unit','key'])
    for exc in act.exchanges():
        if exc['name'] in df.columns:
            df[exc['name']].loc['amount'] += exc.amount
        else:
            df[exc['name']] = [exc.amount, exc.unit, exc.input.key]
    return df.T
```

# PV System


In this section the future candidate has to rely on Part_1 section of PARASOL_LCA model notebook to be able to convert it into the proposed functions. 

PARASOL_LCA model should be open parallelly with this notebook and the candidate should go through PARASOL_LCA function by function (or cell by cell) in order to do the following:
1- In PARASOL_LCA model, detect the functions that generate a change in the original dataset.
For example, the function 'generate_aluminium_alloy_dataset' in the original model is a function that creates a copy of the original aluminum dataset in order to integrate to it additional modification.
2- In PARASOL_LCA model, identify the parameters on which each generating function relies on.
For example, the function 'generate_aluminium_alloy_dataset' in the original model has 2 parameters (or input variables) : 'share_recycled_aluminium' and 'elec_dataset'.
3- The identified input variables should be integrated in the datasetX, especifically in the concerned exchangeX itself using the 'exchangeX['formula']'. It is where the parameters should be integrated with the appropriate mathematical relationship. The person should be careful to revise the original code and understand each line of it to be able to detect each parameter to which dataset it is related.
For example, since the parameter 'share_recycled_aluminium' is connected the following 2 exchanges: exc = 'aluminium, cast alloy' and exc = 'aluminium scrap, new, Recycled Content cut-off', the candidate should stock in the exc['formula'] the corresponding values with their approriate relationship with the parameter as follows:  exc['formula'] = '%f * (1.0 - share_recycled_aluminium)'%(aluminium_amount,).
4- In the optimised version, for each component, at the end of the corresponding section, I compared the original dataset to the adjusted one to be sure that the integrated change is well modeled.
This can serve also the candidate to be reassured of his/her steps.
5- After finishing the transformation of each generating function in the original PARASOL_LCA model into a parameterized function as proposed in the steps 1-4, the candidate will have to stock the parameters in a list called my_parameters = [] as represented in the Notebook 'Parameters_for_Optimised_Model_Sobol_DRAFT1_TANNOUS_Scarlett' . I separated the set of paramters in a separate Notebook just to be visually and technically more practical to have 2 Notebooks on 2 different screens. However, the candidate can stick to 1 Notebook and put them all together in a section. 
In this parmeters' list, the candidate will have to list each parameter and attribute it to the corresponding database, code, name, and amount. 
For example, for the alu_adjusted, the following information will be stocked in the my_paramters[] list:

{'database': alu_adjusted['database'],
 'code': alu_adjusted['code'],
 'name': 'share_recycled_aluminium',
 'amount': 0.0}
 
6- After stocking all the parameters in the list of my_parameter[] in the Notebook 'Parameters_for_Optimised_Model_Sobol_DRAFT1_TANNOUS_Scarlett', the candidate will have to follow the proposed lines of codes in this notebook and try to adjust them according to the added parameters.

7- After finishing the 'parameters' section of 'Parameters_for_Optimised_Model_Sobol_DRAFT1_TANNOUS_Scarlett', the candidate will have to start the execution of the scenarios. At this level, personal effort and researched should be done to understand what is the purpose of each function. However, in order to help at this level, I highly recommend to check the following reference https://salib.readthedocs.io/en/latest/ and go into the details of the Sobol code that Romain Sacchi has extracted and organised in a Notebook called 'Sobol'. At this level, I cannot offer more support as I stopped my investigation here. It is where additional work and research should be done to continue modeling and exploring the functions and the methods available in this library.


## Electricity

```{python}
elec_dataset = [act for act in eidb if 'market group for electricity, medium voltage' == act['name'] and 'ENTSO-E' == act['location']][0]
elec_dataset
```

```{python}
electricity_activity_w_location = [
        {'name': 'market group for electricity, medium voltage', 'location': 'ENTSO-E', 'varname': 'eu_electricity_mix'},
        {'name': 'electricity, high voltage, production mix', 'location': 'CN-GD', 'varname': 'cn_electricity_mix'},
        {'name': 'electricity, high voltage, production mix', 'location': 'FR', 'varname': 'fr_electricity_mix'},
        {'name': 'market for electricity, high voltage', 'location': 'US-WECC', 'varname': 'us_electricity_mix'},
        {'name': 'market for electricity, high voltage', 'location': 'RoW', 'varname': 'row_electricity_mix'}
]

for x in electricity_activity_w_location:
    elec_dataset = [act for act in eidb if x['name'] == act['name'] and x['location'] == act['location']]
    if len(elec_dataset) != 1:
        print("ERROR", x['name'], x['location'])
    x['activity'] = elec_dataset[0]
               
print(electricity_activity_w_location)
```

## Aluminium


### Original dataset

```{python}
alu = [act for act in eidb if 'aluminium alloy production, AlMg3' == act['name']
       and 'RER' in act['location']][0]
alu
```

### Parameterized function

```{python}
def ensure_aluminium_adjusted():
    alu = [act for act in eidb if 'aluminium alloy production, AlMg3' in act['name']and 'RER' in act['location']][0]
    alu_adjusted = [act for act in eidb if 'aluminium alloy production, AlMg3 adjusted' in act['name'] 
                    and 'RoW' in act['location']]
    # Amount of aluminium considered
    for exc in alu.exchanges():
        if exc['name'] == 'aluminium, cast alloy':
            aluminium_amount = exc.amount
    
    if len(adju) == 0:
        alu = [act for act in eidb if 'aluminium alloy production, AlMg3' in act['name']and 'RER' in act['location']][0]
        alu_adjusted = alu.copy()
        alu_adjusted['name'] = 'aluminium alloy production, AlMg3 adjusted'
        alu_adjusted['authors'] = 'Romain Besseau'
        alu_adjusted['comment'] = 'Dataset adjusted with the share of secondary aluminium used and the electricity mix used'
        
        #Adding secondary aluminium
        aluminium_scrap = [act for act in eidb if 'aluminium scrap, new, Recycled Content cut-off' in act['name']][0]

        new_exc = alu_adjusted.new_exchange(input = aluminium_scrap.key, name = aluminium_scrap['name'], 
                                        amount = 0, unit = 'kg', categories = '', type = 'technosphere')
        new_exc.save()
        alu_adjusted.save()
        
    for exc in alu_adjusted.exchanges():
        if exc['name'] == 'aluminium, cast alloy':
            exc['formula'] = '%f * (1.0 - share_recycled_aluminium)'%(aluminium_amount,)
            exc.save()
        if exc['name'] == 'aluminium scrap, new, Recycled Content cut-off':
            exc['formula'] = '%f * (share_recycled_aluminium)'%(aluminium_amount,)
            exc.save()
        
        if exc['name'] == 'electricity, high voltage, aluminium industry':
            electricity_amount = exc
            exc['formula'] = '%f * default_electricity_mix'%(electricity_amount['amount'])
            exc.save()
        
    
    for x in electricity_activity_w_location:
        act = x['activity']
        exc = alu_adjusted.new_exchange(
            input = act.key,
            name="%s %s"%(x['name'], x['location']),
            amount=0.0,
            unit=electricity_amount['unit'],
            category='',
            type=electricity_amount['type'],
            formula='%f * %s'%(electricity_amount['amount'], x['varname']))
        exc.save()
    alu_adjusted.save()    
    
    return alu_adjusted
```

```{python}
alu_adjusted = ensure_aluminium_adjusted()
alu_adjusted
```

```{python}
alu_adjusted = [act for act in eidb if 'aluminium alloy production, AlMg3 adjusted' == act['name']][0]
print_data(alu_adjusted)
```

### Comparision of original and adjusted ds

```{python}
alu_adjusted = [act for act in eidb if 'aluminium alloy production, AlMg3 adjusted' in act['name']][0]
alu_adjusted
```

```{python}
pd.concat([print_data2(alu),print_data2(alu_adjusted)], axis=1)
```

## Mounting system


### Roof


#### Original roof ds

```{python}
roof_system = [act for act in eidb if
               'photovoltaic mounting system production, for slanted-roof installation' == act['name'] 
                and 'RER' in act['location']][0]
roof_system
```

#### Modifying function

```{python code_folding=c()}
def ensure_roof_mounting_system():
    
    roof_system = [act for act in eidb if
                       'photovoltaic mounting system production, for slanted-roof installation' == act['name'] 
                        and 'RER' in act['location']][0]
    
    for exc in roof_system.exchanges():
            if exc['name'] == 'aluminium, wrought alloy':
                aluminium_amount = exc.amount
                
    roof_system_with_recycling = [act for act in eidb if
      'photovoltaic mounting system production, for slanted-roof installation with recycling' == act['name']]
    
    
    if len(roof_system_with_recycling) == 0:
        roof_system = [act for act in eidb if
                       'photovoltaic mounting system production, for slanted-roof installation' == act['name'] 
                        and 'RER' in act['location']][0]
        roof_system_with_recycling = roof_system.copy()
        roof_system_with_recycling['name'] = 'photovoltaic mounting system production, for slanted-roof installation with recycling'
        roof_system_with_recycling['authors'] = 'Romain Besseau'
        roof_system_with_recycling['comment'] = 'Copy of photovoltaic mounting system production, for slanted-roof installation with recycling activites added (scrap steel and scrap aluminium)'
        roof_system_with_recycling.save()
        scrap_aluminium = [act for act in eidb if 'market for scrap aluminium' in act['name']
                                   and 'Europe' in act['location']][0]  
        
        scrap_steel = [act for act in eidb if 'market for scrap steel' 
               in act['name'] and 'Europe' in act['location']][0]

        for exc in roof_system_with_recycling.exchanges():
            if exc['name'] == 'aluminium, wrought alloy':
                aluminium_amount = exc.amount
                new_exc = roof_system_with_recycling.new_exchange(input = scrap_aluminium.key, 
                                                                  name = scrap_aluminium['name'], 
                                                                  amount =  - aluminium_amount,
                                                                  unit = scrap_aluminium['unit'],
                                                                  type = 'technosphere')
                new_exc.save()

            if exc['name'] == 'steel, low-alloyed, hot rolled':
                steel_amout = exc.amount
                new_exc = roof_system_with_recycling.new_exchange(input = scrap_steel.key,
                                                                  name = scrap_steel['name'],
                                                                  amount =  - steel_amout, 
                                                                  unit = scrap_steel['unit'], 
                                                                  type = 'technosphere')
                new_exc.save()


        #add the alu_adjusted with 0 amount
        alu_adjusted = [act for act in eidb if 'aluminium alloy production, AlMg3 adjusted' == act['name']][0]
        new_exc = roof_system_with_recycling.new_exchange(input = alu_adjusted.key,
                                                                  name = alu_adjusted['name'],
                                                                  amount =  0, 
                                                                  unit = alu_adjusted['unit'], 
                                                                  type = 'technosphere')
        new_exc.save()
        roof_system_with_recycling.save()
        
    roof_system_with_recycling = [act for act 
                                  in eidb if
                                  'photovoltaic mounting system production, for slanted-roof installation with recycling'
                                  in act['name']][0]

    for exc in roof_system_with_recycling.exchanges():
        if exc['name'] == 'aluminium, wrought alloy':
            exc['amount'] = 0.0
            exc.save()
        
        if exc['name'] == 'aluminium alloy production, AlMg3 adjusted':
            exc['amount'] = aluminium_amount
            exc.save()
            
    roof_system_with_recycling.save() 
    return roof_system_with_recycling
```

```{python}
roof_system_with_recycling = ensure_roof_mounting_system()
```

```{python}
roof_system_with_recycling
```

#### Comparision original and modified roof ds

```{python}
pd.concat([print_data2(roof_system),print_data2(roof_system_with_recycling)], axis = 1)
```

### Ground


#### Original ground ds

```{python}
ground_system = [act for act in eidb if 'photovoltaic mounting system production, for 570kWp open ground module' in act['name']][0]
ground_system
```

```{python}
print_data(ground_system)
```

#### Modifying ground function

```{python}
ground_system = [act for act in eidb if 
                     'photovoltaic mounting system production, for 570kWp open ground module'
                     in act['name']][0]
```

```{python}
def ensure_ground_mounting_system():
    ground_system = [act for act in eidb if 
                     'photovoltaic mounting system production, for 570kWp open ground module'
                     in act['name']][0]

    ground_system_adjusted = [act for act in eidb 
                              if 'photovoltaic mounting system production, for 570kWp open ground module adjusted' == act['name']]
    
    for exc in ground_system.exchanges():
        if exc['name'] == 'aluminium, wrought alloy':
            aluminium_amount = exc['amount']
    
    if len(ground_system_adjusted) == 0: 
        ground_system = [act for act in eidb if 
                     'photovoltaic mounting system production, for 570kWp open ground module'
                     in act['name']][0]
        ground_system_adjusted = ground_system.copy()
        ground_system_adjusted['name'] = 'photovoltaic mounting system production, for 570kWp open ground module adjusted'
        ground_system_adjusted['authors'] = 'Romain Besseau'
        ground_system_adjusted['comment'] = 'Dataset adjusted with the share of secondary aluminium used and the recycling rate'
        ground_system_adjusted.save()
        #Changing the aluminium dataset to the adjusted one.
        alu_adjusted = [act for act in
                eidb if 'aluminium alloy production, AlMg3 adjusted' == act['name']][0]
        
        new_exc = ground_system_adjusted.new_exchange(input = alu_adjusted.key,
                                                      name = alu_adjusted['name'],
                                                      amount =  0, 
                                                      unit = alu_adjusted['unit'], 
                                                      type = 'technosphere')
        new_exc.save()
        ground_system_adjusted.save()       
        
        for exc in ground_system_adjusted.exchanges():
            if exc['name'] == 'aluminium, wrought alloy':
                exc['amount'] = 0
                exc.save()      
                
            if exc['name'] == 'aluminium alloy production, AlMg3 adjusted':
                exc['amount'] = aluminium_amount
                exc.save()           

        ground_system_adjusted.save() 
        
    else:
        ground_system_adjusted = [act for act in eidb 
          if 'photovoltaic mounting system production, for 570kWp open ground module adjusted' == act['name']][0]
        
    return ground_system_adjusted
```

```{python}
ground_system_adjusted = ensure_ground_mounting_system()
```

```{python}
print_data2(ground_system_adjusted)
```

#### Comparision original and modified ground ds

```{python}
pd.concat([print_data2(ground_system),print_data2(ground_system_adjusted)], axis = 1)
```

```{python}
add the 2 of them:
act['fomrula'] = %f roof (this is o or 1) %(amount)
```

## Electrical Installation

```{python}
electrical_installation_3kW = [act for act in eidb if 'photovoltaics, electric installation for 3kWp module, at building' == act['name'] and 'RoW' in act['location']][0]
electrical_installation_3kW
```

```{python}
unit_of_equivalent_3kW_electrical_installation = InterpolatedUnivariateSpline([3, 570],
                                                                              [33/33, 
                                                                               1570/33],
                                                                              k=1)
unit_of_equivalent_3kW_electrical_installation(10)
```

## Inverter

```{python}
(P = 10, elec_dataset = None, recycling_rate = 0)
```

### Inverter 2.5kW

```{python}
alkyl_paint = [act for act in eidb if 'alkyd paint, white, without solvent, in 60% solution state' in act['name']][0]
glass_fiber = [act for act in eidb if 'glass fibre reinforced plastic, polyamide, injection moulded' in act['name']][0]
glass_plastic = [act for act in eidb if 'glass fibre reinforced plastic, polyester resin, hand lay-up' in act['name']][0]
injection_moulding = [act for act in eidb if 'injection moulding' in act['name'] and 'GLO' in act['location']][0]
lubricating_oil = [act for act in eidb if 'lubricating oil' in act['name'] and 'GLO' in act['location']][0]
polyethylene = [act for act in eidb if 'polyethylene, high density, granulate' in act['name'] and 'GLO' in act['location']][0]
waste_mineral = [act for act in eidb if 'market for waste mineral oil' in act['name'] and 'Europe' in act['location']][0]
waste_plastic = [act for act in eidb if 'market for waste plastic, industrial electronics' in act['name']][0]
```

```{python}
act = [act for act in eidb if 'alkyd paint, white, without solvent, in 60% solution state' in act['name']][0]
act = [act for act in eidb if 'glass fibre reinforced plastic, polyamide, injection moulded' in act['name']][0]
act = [act for act in eidb if 'glass fibre reinforced plastic, polyester resin, hand lay-up' in act['name']][0]
act = [act for act in eidb if 'injection moulding' in act['name'] and 'GLO' in act['location']][0]
act = [act for act in eidb if 'lubricating oil' in act['name'] and 'GLO' in act['location']][0]
act = [act for act in eidb if 'polyethylene, high density, granulate' in act['name'] and 'GLO' in act['location']][0]
act = [act for act in eidb if 'market for waste mineral oil' in act['name'] and 'Europe' in act['location']][0]
act = [act for act in eidb if 'market for waste plastic, industrial electronics' in act['name']][0]
```

```{python}
def ensure_inverter_2_5kW():
    inverter_2_5kW = [act for act in eidb if 'inverter production, 2.5kW' in act['name'] and 'RER' in act['location']][0]
    inverter_2_5kW_adjusted = [act for act in eidb if 'inverter production, 2.5kW adjusted' in act['name'] and 'RER' in act['location']]
    

    if len(inverter_2_5kW_adjusted) == 0:
        inverter_2_5kW_adjusted = inverter_2_5kW.copy()
        inverter_2_5kW_adjusted['name'] = 'inverter production, 2.5kW adjusted'
        inverter_2_5kW_adjusted['location'] = 'RER' 
        inverter_2_5kW_adjusted['author'] = 'Scarlett Tannous'
        inverter_2_5kW_adjusted['comment'] = 'the exchanges missing from inverter production, 2.5kW and presend in inverter production, 500kW were added' 
        inverter_2_5kW_adjusted.save()
        
        #activities present in inverter 500kW but not in 2.5kW
        act = [act for act in eidb if 'alkyd paint, white, without solvent, in 60% solution state' in act['name']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'glass fibre reinforced plastic, polyamide, injection moulded' in act['name']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'glass fibre reinforced plastic, polyester resin, hand lay-up' in act['name']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'injection moulding' in act['name'] and 'GLO' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'lubricating oil' in act['name'] and 'GLO' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'polyethylene, high density, granulate' in act['name'] and 'GLO' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'market for waste mineral oil' in act['name'] and 'Europe' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        act = [act for act in eidb if 'market for waste plastic, industrial electronics' in act['name']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
                   
        #adding the recycling
        #scrap aluminium
        act = [act for act in eidb if 'market for scrap alu' in act['name'] and 'Europe' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        #scrap steel
        act = [act for act in eidb if 'market for scrap steel' in act['name'] and 'Europe' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        #scrap copper
        act = [act for act in eidb if 'market for scrap copper' in act['name'] and 'Europe' in act['location']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
       
        #scrap electronic
        act = [act for act in eidb if 'market for electronics scrap' in act['name']][0]
        new_exc = inverter_2_5kW_adjusted.new_exchange(input = act.key, name = act['name'], amount = 0, unit = act['unit'], type = 'technosphere')
        new_exc.save()
        
        inverter_2_5kW_adjusted.save()
        
        #electricity mix
        for exc in inverter_2_5kW_adjusted.exchanges():
            if exc['name'] == 'electricity, medium voltage':
                electricity_amount = exc
                exc['formula'] = '%f * default_electricity_mix'%(electricity_amount['amount'])
                exc.save()
          
        for x in electricity_activity_w_location:
            act = x['activity']
            exc = inverter_2_5kW_adjusted.new_exchange(
                input = act.key,
                name="%s %s"%(x['name'], x['location']),
                amount=0.0,
                unit=electricity_amount['unit'],
                category='',
                type=electricity_amount['type'],
                formula='%f * %s'%(electricity_amount['amount'], x['varname']))
            exc.save()
        inverter_2_5kW_adjusted.save()
        

        #recycling activities
        m_aluminium = 0
        m_copper = 0
        m_steel = 0
        m_electronic = 0
        #recycling_rate = 0

        for exc in inverter_2_5kW_adjusted.exchanges():
            if exc['name'] == 'aluminium, cast alloy':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_aluminium += exc['amount']
            if exc['name'] == 'copper':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_copper += exc['amount']
            if exc['name'] == 'steel, low-alloyed, hot rolled':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_steel += exc['amount']
            if ('capacitor' in exc['name']) or ('diode' in exc['name']) or ('integrated circuit' in exc['name']) or ('printed wiring' in exc['name']) or ('resistor' in exc['name']) or ('transistor' in exc['name']):
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_electronic += exc['amount']
            exc.save()
        
        inverter_2_5kW_adjusted.save()

    else:
        inverter_2_5kW_adjusted = [act for act in eidb if 'inverter production, 2.5kW adjusted' in act['name']][0]
    
    return inverter_2_5kW_adjusted
```

```{python}
inverter_2_5kW = [act for act in eidb if 'inverter production, 2.5kW' in act['name'] and 'RER' in act['location']][0]
inverter_2_5kW
```

```{python}
inverter_2_5kW_adjusted = [act for act in eidb if 'inverter production, 2.5kW adjusted' in act['name']][0]
inverter_2_5kW_adjusted
```

```{python}
inverter_2_5kW_adjusted = ensure_inverter_2_5kW()
inverter_2_5kW_adjusted 
```

```{python}
print_data2(inverter_2_5kW_adjusted)
```

the 2.5kW weighs 18.5 kg and the 500kW weighs 3000 kg.


### Inverter 500kW

```{python}
PVC = [act for act in eidb if 'polyvinylchloride, suspension polymerised' in act['name'] and 'GLO' in act['location']][0]     
SAC = [act for act in eidb if 'styrene-acrylonitrile copolymer' in act['name'] and 'GLO' in act['location']][0]
```

```{python}
def ensure_inverter_500kW():
    inverter_500kW = [act for act in eidb if 'inverter production, 500kW' in act['name'] and not 'car' in act['name'] and 'RER' in act['location']][0]
    inverter_500kW_adjusted = [act for act in eidb if 'inverter production, 500kW adjusted' == act['name']]
    
    if len(inverter_500kW_adjusted) == 0:
        inverter_500kW_adjusted = inverter_500kW.copy()
        inverter_500kW_adjusted['name'] = 'inverter production, 500kW adjusted'
        inverter_500kW_adjusted['location'] = 'RER' 
        inverter_500kW_adjusted['author'] = 'Scarlett Tannous'
        inverter_500kW_adjusted['comment'] = 'the exchanges missing from inverter production, 500kW and presend in inverter production, 500kW were added' 
        inverter_500kW_adjusted.save()
        
        #activities present in inverter 500kW but not in 2.5kW
        act = [act for act in eidb 
               if 'polyvinylchloride, suspension polymerised' in act['name'] and 'GLO' in act['location']][0]      
        new_exc = inverter_500kW_adjusted.new_exchange(input = act.key, 
                                                       name = act['name'], 
                                                       amount = 0, unit = act['unit'],
                                                       type = 'technosphere')
        new_exc.save()
          
        act = [act for act in eidb
               if 'styrene-acrylonitrile copolymer' in act['name'] and 'GLO' in act['location']][0]
        new_exc = inverter_500kW_adjusted.new_exchange(input = act.key, 
                                                       name = act['name'], 
                                                       amount = 0, unit = act['unit'],
                                                       type = 'technosphere')
        new_exc.save()
        inverter_500kW_adjusted.save()
        
        
        #electricity mix
        for exc in inverter_500kW_adjusted.exchanges():
            if exc['name'] == 'electricity, medium voltage':
                electricity_amount = exc
                exc['formula'] = '%f * default_electricity_mix'%(electricity_amount['amount'])
                exc.save()
          
        for x in electricity_activity_w_location:
            act = x['activity']
            exc = inverter_500kW_adjusted.new_exchange(
                input = act.key,
                name="%s %s"%(x['name'], x['location']),
                amount=0.0,
                unit=electricity_amount['unit'],
                category='',
                type=electricity_amount['type'],
                formula='%f * %s'%(electricity_amount['amount'], x['varname']))
            exc.save()
        inverter_500kW_adjusted.save()
        

        #recycling activities
        m_aluminium = 0
        m_copper = 0
        m_steel = 0
        m_electronic = 0
        recycling_rate = 0

        for exc in inverter_500kW_adjusted.exchanges():
            if exc['name'] == 'aluminium, cast alloy':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_aluminium += exc['amount']
            if exc['name'] == 'copper':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_copper += exc['amount']
            if exc['name'] == 'steel, low-alloyed, hot rolled':
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_steel += exc['amount']
            if ('capacitor' in exc['name']) or ('diode' in exc['name']) or ('integrated circuit' in exc['name']) or ('printed wiring' in exc['name']) or ('resistor' in exc['name']) or ('transistor' in exc['name']):
                exc['formula'] = '%f*%s'%(exc['amount'],recycling_rate)
                m_electronic += exc['amount']
            exc.save()
        
        inverter_500kW_adjusted.save()
        
    else:
        inverter_500kW_adjusted = [act for act in eidb if 'inverter production, 500kW adjusted' == act['name'] and 'RER' in act['location']][0]
     
    return inverter_500kW_adjusted
```

```{python}
inverter_500kW_adjusted = ensure_inverter_500kW()
```

```{python}
inverter_500kW_adjusted = [act for act in eidb if 'inverter production, 500kW adjusted' in act['name']][0]
print_data(inverter_500kW_adjusted)
```

### Comparision of inverters 2.5kW and 500kW

```{python}
pd.concat([print_data2(inverter_2_5kW_adjusted),print_data2(inverter_500kW_adjusted)], axis = 1)
```

```{python}
def ensure_inverter_P_per_kg():
    
    inverter_500kW = [act for act in eidb if 'inverter production, 500kW' in act['name'] and not 'car' in act['name'] and 'RER' in act['location']][0]
    inverter_P_per_kg = [act for act in eidb if 'Inverter production, P kW per kg' in act['name']]
    
    if len(inverter_P_per_kg)==0:
        inverter_P_per_kg = inverter_500kW.copy()
        inverter_P_per_kg['name'] = 'Inverter production, P kW per kg'
        inverter_P_per_kg['unit'] = 'kilogram'
        inverter_P_per_kg['authors'] = 'Romain Besseau'
        inverter_P_per_kg['comment'] = 'Dataset based on the inventories of 3 kVA and 500 kVA PV inverters. It gives the inventory per inverter kilogram depending on the rated power P and considering a linear extrapolation between 3 kVA and 500 kVA inventories that do not have the same material ratio. The impact per kW will then be calculated considering 2 kg of inverter per kW (based on the analysis of ABB PV inverters). PS: With technical improvements the ratio weight power tends to decrease.'
        inverter_P_per_kg.save()
        
        
        #Removing all data
        for exc in inverter_P_per_kg.exchanges():
            exc.delete()
        inverter_P_per_kg.save()

        #adding the 2 inverters
        inverter_2_5kW_adjusted = [act for act in eidb if 'inverter production, 2.5kW adjusted' in act['name']][0]
        new_exc = inverter_P_per_kg.new_exchange(input = inverter_2_5kW_adjusted.key, 
                                                name = inverter_2_5kW_adjusted['name'], 
                                                amount = 1/18.5, 
                                                unit = inverter_2_5kW_adjusted['unit'],
                                                type = 'technosphere',
                                                #2*P represents the mass
                                                 formula = '(2*P)*((P-2.5)/(500-2.5))* (1/18.5)'
                                                )
        new_exc.save()
        
        inverter_500kW_adjusted = [act for act in eidb if 'inverter production, 500kW adjusted' in act['name']][0]
        new_exc = inverter_P_per_kg.new_exchange(input = inverter_500kW_adjusted.key, 
                                                   name = inverter_500kW_adjusted['name'], 
                                                   amount = 1/3000, unit = inverter_500kW_adjusted['unit'],
                                                   type = 'technosphere',
                                                 formula = '(2*P)*(1- ((P-2.5)/(500-2.5)))* (1/3000)'
                                                )

        new_exc.save()
        inverter_P_per_kg.save()
    
    
    else:
        inverter_P_per_kg = [act for act in eidb if 'Inverter production, P kW per kg' == act['name']][0]
        
    
    return inverter_P_per_kg
```

```{python}
inverter_P_per_kg = ensure_inverter_P_per_kg()
```

```{python}
inverter_P_per_kg 
```

```{python}
ActivityParameter.update(amount=0.0).where(ActivityParameter.name == "eu_electricity_mix").execute()
```

```{python}
inverter_P_per_kg = [act for act in eidb if 'Inverter production, P kW per kg' in act['name']][0]
inverter_P_per_kg
```

```{python}

```

```{python}
value = np.interp(P, [3, 500], df_inverter_share.loc[exc][['3 kW share', '500 kW share']].values)
```

```{python}
print_data(inverter_P_per_kg)
```

the idea is to have 2 uniform datasets where all the parameterized ds are set in the forumla
create 1 dataset including the 2.5 and the 500 and monitoring the amounts by the formla of the interpolation
the putting the created dataset in the final dictionary where the amount of inverter is controlled by the PV_lifetime and the inverter_lifetime

```{python}
#To check with BG
```

## Metallization paste


### Original metallization ds

```{python}
metal_paste = [act for act in eidb if 'metallization paste production, back side' == act['name'] and 'RER' in act['location'] and not 'aluminium' in act['name']][0]
metal_paste   
```

### Modifying function metallization

```{python}
#Create a new metalization paste copper based

def ensure_copper_metallization_paste():

    metal_paste_copper = [act for act in eidb if 'metallization paste production, back side, copper' == act['name'] and not 'aluminium' in act['name']]

    if len(metal_paste_copper) == 0: 
        metal_paste = [act for act in eidb if 'metallization paste production, back side' == act['name'] and 'RER' in act['location'] and not 'aluminium' in act['name']][0]
        metal_paste_copper = metal_paste.copy()
        metal_paste_copper['name'] = 'metallization paste production, back side, copper'
        metal_paste_copper['authors'] = 'Romain Besseau'
        metal_paste_copper['comment'] = 'Dataset for metallization paste production where Silver is simply replaced by Copper'

        for exc in metal_paste_copper.exchanges():
            exc['output'] = metal_paste_copper.key
            exc.save()

        copper_dataset = [act for act in eidb if 'copper production, primary' == act['name'] and 'RoW' in act['location']][0]
        #Changing the silver dataset to copper.               
        for exc in metal_paste_copper.exchanges():
            if exc['name'] == 'silver':
                exc['name'] = copper_dataset['name']
                exc['input'] = copper_dataset.key
                exc.save()  
        metal_paste_copper.save()  
    else: 
        metal_paste_copper = [act for act in eidb if 'metallization paste production, back side, copper' in act['name'] ][0]
    return metal_paste_copper
```

```{python}
metal_paste_copper = ensure_copper_metallization_paste()
```

```{python}
metal_paste_copper = [act for act in eidb if 'metallization paste production, back side, copper' in act['name']][0]
metal_paste_copper 
```

### Comparision of original and modified metallization paste

```{python}
pd.concat([print_data2(metal_paste),print_data2(metal_paste_copper)], axis=1)
```

## Silicon


### Original silicon dataset

```{python}
silicon_original = [act for act in eidb if 'silicon production, solar grade, modified Siemens process'  in act['name'] and 'RER' in act['location']][0]
print_data(silicon_original)
```

### Parameterized silicon function

```{python}
def ensure_silicon_adjusted():
    silicon_original = [act for act in eidb if 'silicon production, solar grade, modified Siemens process'  in act['name'] and 'RER' in act['location']][0]
    silicon_adjusted = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' == act['name']]
    
    if len(silicon_adjusted) == 0:
        silicon_original = [act for act in eidb if 'silicon production, solar grade, modified Siemens process'  in act['name'] and 'RER' in act['location']][0]
        silicon_adjusted = silicon_original.copy()
        silicon_adjusted['name'] = 'silicon production, solar grade, modified Siemens process adjusted'
        silicon_adjusted['authors'] = 'Romain Besseau'
        silicon_adjusted['comment'] = 'Dataset adjusted with the amount of electricity and the corresponding dataset'      
        
        
        #Deleting hydro dataset not to count two times electricity
        # Elec dataset to remove to avoid double amount of electricity
        elec_hydro = [act for act in eidb if 'electricity production, hydro, run-of-river' in act['name'] and 'RoW' in act['location']][0]

        for exc in silicon_adjusted.exchanges():
            if exc['unit'] == 'kilowatt hour':
                if exc['activity'] == elec_hydro['activity']:
                    exc['amount'] = 0
                    exc.save()
        
        silicon_adjusted.save()
        
        ##################################
        for exc in silicon_adjusted.exchanges():
            if exc['name'] == 'electricity, high voltage':
                electricity_amount = exc
                exc['formula'] = 'silicon_electricity_intensity * default_electricity_mix'
                exc.save()
        silicon_adjusted.save() 
        
        for x in electricity_activity_w_location:
            act = x['activity']
            exc = inverter_500kW_adjusted.new_exchange(
                input = act.key,
                name="%s %s"%(x['name'], x['location']),
                amount=0.0,
                unit=electricity_amount['unit'],
                category='',
                type=electricity_amount['type'],
                formula='%f * %s'%(electricity_amount['amount'], x['varname']))
            exc.save()
        silicon_adjusted.save()
    else:
        #silicon = [act for act in eidb if initial_dataset in act['name'] and 'RER' in act['location']][0]
        silicon_adjusted = [act for act in eidb if initial_dataset + ' adjusted' in act['name']][0]
    
    return silicon_adjusted
```

```{python}
silicon_adjusted = ensure_silicon_adjusted()
```

```{python}
silicon_adjusted = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' in act['name']][0]
print_data(silicon_adjusted)
```

### Comparision of original and modified silicon ds

```{python}
pd.concat([print_data2(silicon_original),print_data2(silicon_adjusted)], axis=1)
```

## Wafer manufacturing


### Cutting process


#### Silicon carbide recycled

```{python}
def generate_SiC_recycled_dataset():
    
    if [act for act in eidb if 'silicon carbide, recycled production' == act['name']] == []:
        act_original= [act for act in eidb if 'silicon carbide production' in act['name'] and 'RER' in act['location']][0]
        SiC_recycled=act_original.copy()
        SiC_recycled['name'] = 'silicon carbide, recycled production'
        SiC_recycled['unit'] = 'kilogram'
        SiC_recycled['author'] = 'ST based on KBOB:2016'
        SiC_recycled['location'] = 'RER'
        SiC_recycled['comment'] = 'Dataset corresponding to the Silicon carbide, recycling, at plant/kg/RER of the KBOB:2016'
        
        #Removing all data
        for exc in SiC_recycled.exchanges():
            exc.delete()
            exc.save()
        SiC_recycled.save()
        
        #Output
        act = [act for act in eidb if 'silicon carbide, recycled production' in act['name']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = 1, unit = 'kilogram', type = 'production', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Electricity input
        act =[act for act in eidb if 'market group for electricity, medium voltage' in act['name'] and 'ENTSO' in act['location']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = 0.78571, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Transport input
        act = [act for act in eidb if 'market for transport, freight, lorry, unspecified' in act['name'] and 'GLO' in act['location']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = 0.2625, unit = 'ton kilometer', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Silicon input
        act = [act for act in eidb if 'market for silicone factory' in act['name']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = 1e-11, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Emissions to air
        act = [act for act in bio3 if 'Heat, waste' == act['name'] and "air" in act['categories'] and len(act['categories'])==1][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = 2.8286, unit = 'megajoule', type = 'biosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Disposal Si
        act = [act for act in eidb if 'market for waste, from silicon wafer production, inorganic' in act['name']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = -0.042857, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Disposal antifreezer
        #This had double impact:
        #act = [act for act in eidb if 'market for spent antifreezer liquid' in act['name'] and 'GLO' in act['location']][0]
        #This should be used because it is not CH only
        #act = [act for act in eidb if 'treatment of spent antifreezer liquid, hazardous waste incineration' in act['name'] and 'RoW' in act['location']][0]
        act = [act for act in eidb if 'treatment of spent antifreezer liquid, hazardous waste incineration' in act['name'] and 'CH' in act['location']][0]
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = -0.071429, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        #Disposal pig iron
        act = [act for act in eidb if 'market for sludge, pig iron production' in act['name'] and 'Europe' in act['location']][0] 
        new_exc = SiC_recycled.new_exchange(input = act.key, amount = -0.13571, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        SiC_recycled.save()
        
        
    else:
        act_original= [act for act in eidb if 'silicon carbide production' in act['name'] and 'RER' in act['location']][0]
        SiC_recycled = [act for act in eidb if 'silicon carbide, recycled production' == act['name']][0]
                
    return SiC_recycled
```

```{python}
SiC_recycled = generate_SiC_recycled_dataset()
print_data(SiC_recycled)
```

```{python}
SiC_recycled = [act for act in eidb if 'silicon carbide, recycled production' in act['name']][0]
SiC_recycled
```

#### Ethylene glycol recycled 

```{python}
def generate_TEG_recycled_dataset():
    
    if [act for act in eidb if 'triethylene glycol, recycled production' == act['name']] == []:
        act_original= [act for act in eidb if 'ethylene glycol production' in act['name'] and 'RER' in act['location']][0]
        TEG_recycled=act_original.copy()
        TEG_recycled['name'] = 'triethylene glycol, recycled production'
        TEG_recycled['unit'] = 'kilogram'
        TEG_recycled['author'] = 'ST based on KBOB:2016'
        TEG_recycled['location'] = 'RER'
        TEG_recycled['comment'] = 'Dataset corresponding to the Triethylene glycol, recycling, at plant/RER of the KBOB:2016'
        
        #Removing all data
        for exc in TEG_recycled.exchanges():
            exc.delete()
            exc.save()
        TEG_recycled.save()
        
        #Output
        act = [act for act in eidb if 'triethylene glycol, recycled production' in act['name']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = 1, unit = 'kilogram', type = 'production', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Electricity input
        act =[act for act in eidb if 'market group for electricity, medium voltage' in act['name'] and 'ENTSO' in act['location']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = 0.78571, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Transport input
        act = [act for act in eidb if 'market for transport, freight, lorry, unspecified' in act['name'] and 'GLO' in act['location']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = 0.2625, unit = 'ton kilometer', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Silicon input
        act = [act for act in eidb if 'market for silicone factory' in act['name']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = 1e-11, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Emissions to air
        act = [act for act in bio3 if 'Heat, waste' in act['name'] and "air" in act['categories'] and 'f2d84834-d0b3-42e5-b41a-f04cc80337a4' in act['code']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = 2.8286, unit = 'megajoule', type = 'biosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Disposal Si
        act = act = [act for act in eidb if 'market for waste, from silicon wafer production, inorganic' in act['name']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = -0.042857, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Disposal antifreezer
        #This had double impact:
        #act = [act for act in eidb if 'market for spent antifreezer liquid' in act['name'] and 'GLO' in act['location']][0]
        #This should be used because it is not CH only
        #act = [act for act in eidb if 'treatment of spent antifreezer liquid, hazardous waste incineration' in act['name'] and 'RoW' in act['location']][0]
        act = [act for act in eidb if 'treatment of spent antifreezer liquid, hazardous waste incineration' in act['name'] and 'CH' in act['location']][0]
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = -0.071429, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        #Disposal pig iron
        act = [act for act in eidb if 'market for sludge, pig iron production' in act['name'] and 'Europe' in act['location']][0] 
        new_exc = TEG_recycled.new_exchange(input = act.key, amount = -0.13571, unit = 'unit', type = 'technosphere', name = act['name'])
        new_exc.save()
        TEG_recycled.save()
        
        
    else:
        act_original= [act for act in eidb if 'ethylene glycol production' in act['name'] and 'RER' in act['location']][0]
        TEG_recycled = [act for act in eidb if 'triethylene glycol, recycled production' == act['name']][0]
                
    return TEG_recycled
```

```{python}
TEG_recycled = generate_TEG_recycled_dataset()
TEG_recycled
```

```{python}
TEG_recycled = [act for act in eidb if 'triethylene glycol, recycled production' in act['name']][0] 
TEG_recycled
```

#### Diamond wiring

```{python}
def generate_tungsten():
    '''
    This function generates a new dataset the tungsten carbide (expressed in kg) which is used for the wire later on.
    '''
    
    if [act for act in eidb if 'tungsten carbide production' == act['name']] == []:
        act_original=[act for act in eidb if 'silicon carbide production' == act['name'] and 'RER' in act['location']][0]
        tungsten_carbide=act_original.copy()
        tungsten_carbide['name'] = 'tungsten carbide production'
        tungsten_carbide['unit'] = 'kilogram'
        tungsten_carbide['location'] = 'RER'
        tungsten_carbide['author'] = 'ST based on Isabella Bianco dataset'
        tungsten_carbide['comment'] = 'Dataset corresponding to the LCI provided by Isabella Bianco(2018) thesis - Table 46'
        
        #Removing all data
        for exc in tungsten_carbide.exchanges():
            exc.delete()
            exc.save()
        tungsten_carbide.save()
        
        #Output
        act = [act for act in eidb if 'tungsten carbide production' in act['name']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 1, unit = 'kilogram', type = 'production', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        #input
        act = [act for act in eidb if 'market for sodium hydroxide, without water, in 50% solution state' in act['name'] and 'GLO' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 1.49, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'aluminium sulfate production, powder' in act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.071, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'sodium sulfide production' in act['name'] and 'GLO' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.044, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'magnesium sulfate production' in act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.027, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'market for ammonia, liquid' in act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.106, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'market for soda ash, dense' in act['name'] and 'GLO' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 1.21, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'sulfuric acid production' == act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 1.24, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'market group for electricity, medium voltage' in act['name'] and 'ENTSO-E' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 111.16, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'hydrogen sulfide production' == act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.0076, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'market for nitrogen, liquid' == act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 1.65, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'market for hydrogen, liquid' in act['name'] and 'RER' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.32, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()        
        
        act = [act for act in eidb if 'market for tap water' in act['name'] and 'RoW' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 2.84, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
        act = [act for act in eidb if 'carbon black production' == act['name'] and 'GLO' in act['location']][0]
        new_exc = tungsten_carbide.new_exchange(input = act.key, amount = 0.13, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        tungsten_carbide.save()
        
    else:
        tungsten_carbide = [act for act in eidb if 'tungsten carbide production' == act['name']][0]
        
    return tungsten_carbide  
```

```{python}
tungsten_carbide = generate_tungsten()
```

```{python}
tungsten_carbide = [act for act in eidb if 'tungsten carbide production' in act['name']][0]
tungsten_carbide
```

```{python}
def generate_diamond_powder():
    '''
    This function generates a new dataset of diamond powder which is used for the wire later on.
    '''
    
    if [act for act in eidb if 'diamond powder, production' == act['name']] == []:
        act_original= [act for act in eidb if 'sodium percarbonate production, powder' in act['name'] and 'RER' in act['location']][0]
        diamond_powder=act_original.copy()
        diamond_powder['name'] = 'diamond powder, production'
        diamond_powder['unit'] = 'kilogram'
        diamond_powder['location'] = 'RER'
        diamond_powder['author'] = 'ST based on Isabella Bianco dataset'
        diamond_powder['comment'] = 'Dataset corresponding to the LCI provided by Isabella Bianco(2018) thesis - Table 51'
        
        #Removing all data
        for exc in diamond_powder.exchanges():
            exc.delete()
            exc.save()
        diamond_powder.save()
        
        #Output
        act = [act for act in eidb if 'diamond powder, production' in act['name']][0]
        new_exc = diamond_powder.new_exchange(input = act.key, amount = 1, unit = 'kilogram', type = 'production', name = act['name'])
        new_exc.save()
        diamond_powder.save()
        
        #input
        act = [act for act in eidb if 'market for electricity, medium voltage' in act['name'] and 'CN-CSG' in act['location']][0]
        new_exc = diamond_powder.new_exchange(input = act.key, amount = 840, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        diamond_powder.save()
        
        act = [act for act in eidb if 'graphite production' in act['name'] and 'RER' in act['location']][0]
        new_exc = diamond_powder.new_exchange(input = act.key, amount = 1, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        diamond_powder.save()
        
        #transport from China to Europe (Italy, for example)
        act = [act for act in eidb if 'transport, freight, sea, transoceanic ship' == act['name'] and 'GLO' in act['location']][0]
        new_exc = diamond_powder.new_exchange(input = act.key, amount = 170, unit = 'ton kilometer', type = 'technosphere', name = act['name'])
        new_exc.save()
        diamond_powder.save()
        
        act = [act for act in eidb if 'transport, freight, lorry 16-32 metric ton, EURO4' == act['name'] and 'RER' in act['location']][0]
        new_exc = diamond_powder.new_exchange(input = act.key, amount = 0.53, unit = 'ton kilometer', type = 'technosphere', name = act['name'])
        new_exc.save()
        diamond_powder.save()
        
    else:
        diamond_powder = [act for act in eidb if 'diamond powder, production' == act['name']][0]
        
    return diamond_powder
```

```{python}
diamond_powder = generate_diamond_powder()
```

```{python}
diamond_powder = [act for act in eidb if  'diamond powder, production' in act['name']][0]
diamond_powder 
```

```{python}
def generate_sintered_diamond_bead():
    
    '''
    This function generates a new dataset of sintered diamond which is used for the wire later on.
    The paramater elec_dataset permits the control of the electricity used for manufacturing.
    '''
    
    if [act for act in eidb if 'sintered diamond bead, for quarrying' == act['name']] == []:
        act_original= [act for act in eidb if  'polymethyl methacrylate production, beads' == act['name'] and 'RER' in act['location']][0]
        sintered_diamond_bead=act_original.copy()
        sintered_diamond_bead['name'] = 'sintered diamond bead, for quarrying'
        sintered_diamond_bead['unit'] = 'kilogram'
        sintered_diamond_bead['location'] = 'RER'
        sintered_diamond_bead['author'] = 'ST based on Isabella Bianco dataset'
        sintered_diamond_bead['comment'] = 'Dataset corresponding to the LCI provided by Isabella Bianco(2018) thesis - Table 50'
        
        #Removing all data
        for exc in sintered_diamond_bead.exchanges():
            exc.delete()
            exc.save()
        sintered_diamond_bead.save()
        
        #Output
        act = [act for act in eidb if 'sintered diamond bead, for quarrying' in act['name']][0]
        new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 0.004, unit = 'kilogram', type = 'production', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
    
        #the input of the sintered diamond bead (table 50 of Isabella Bianco thesis) to be integrated to Table 45
        
        act = [act for act in eidb if 'market group for electricity, medium voltage' == act['name'] and 'ENTSO-E' == act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 0.1, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for steel, unalloyed' in act['name'] and 'GLO' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 0.003, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for cobalt' in act['name'] and 'GLO' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 7e-08, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()    
        
        act = [act for act in eidb if 'market for copper' == act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 2.1e-07, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if  'market for pig iron' == act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 3.5e-07, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for nickel, 99.5%' == act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 2.1e-08, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'tungsten carbide production' == act['name'] and 'RER' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 3.5e-08, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'diamond powder, production' == act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 2e-05, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if  'polymethyl methacrylate production, beads' == act['name'] and 'RER' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 2e-05, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'cobalt production' == act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 5e-05, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for silver' in act['name']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 2.1e-04, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for nitrogen, liquid' in act['name'] and 'RER' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 0.0323, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
        
        act = [act for act in eidb if 'market for hydrogen, liquid' in act['name'] and 'RER' in act['location']][0]
        new_exc = new_exc = sintered_diamond_bead.new_exchange(input = act.key, amount = 9e-04, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_diamond_bead.save()
    
    else:
        sintered_diamond_bead = [act for act in eidb if 'sintered diamond bead, for quarrying' == act['name']][0]
                
    return sintered_diamond_bead 
```

```{python}
sintered_diamond_bead = generate_sintered_diamond_bead()
sintered_diamond_bead = [act for act in eidb if 'sintered diamond bead, for quarrying' in act['name']][0]
```

```{python}
sintered_diamond_bead = [act for act in eidb if 'sintered diamond bead, for quarrying' in act['name']][0]
sintered_diamond_bead 
```

```{python}
def generate_DW_single_electroplated():
    
    '''
    This function generates a new dataset represented the electroplated diamond wire used for the cutting process of the wafer.
    The paramater elec_dataset permits the control of the electricity used for manufacturing.
    '''
    
    if [act for act in eidb if 'sintered diamond wire, steel' == act['name']] == []:
        act_original= [act for act in eidb if 'wire drawing, steel' in act['name'] and 'RER' in act['location']][0]
        sintered_DW=act_original.copy()
        sintered_DW['name'] = 'sintered diamond wire, steel'
        sintered_DW['unit'] = 'meter'
        sintered_DW['location'] = 'RER'
        sintered_DW['author'] = 'ST based on Isabella Bianco dataset'
        sintered_DW['comment'] = 'Dataset corresponding to the LCI provided by Isabella Bianco(2018) thesis - Table 47'
        
        #Removing all data
        for exc in sintered_DW.exchanges():
            exc.delete()
            exc.save()
        sintered_DW.save()
        
        #Output
        act = [act for act in eidb if 'sintered diamond wire, steel' in act['name']][0]
        new_exc = sintered_DW.new_exchange(input = act.key, amount = 1, unit = 'meter', type = 'production', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        #the input of the sintered diamond wire for primapry cuttings (Table 47)
        act = [act for act in eidb if 'sintered diamond bead, for quarrying' in act['name']][0]
        new_exc =  sintered_DW.new_exchange(input = act.key, amount = 0.0427, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        act = [act for act in eidb if 'market group for electricity, medium voltage' == act['name'] and 'ENTSO-E' == act['location']][0]
        new_exc = sintered_DW.new_exchange(input = act.key, amount = 0.9, unit = 'kilowatt hour', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        act = [act for act in eidb if 'wire drawing, steel' == act['name'] and 'RER' in act['location']][0]
        new_exc =  sintered_DW.new_exchange(input = act.key, amount = 0.095, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        act = [act for act in eidb if 'polyurethane production, flexible foam' in act['name'] and 'RER' in act['location']][0]
        new_exc =  sintered_DW.new_exchange(input = act.key, amount = 0.15, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        act = [act for act in eidb if 'transport, freight, lorry 16-32 metric ton, EURO4' == act['name'] and 'RER' in act['location']][0]
        new_exc =  sintered_DW.new_exchange(input = act.key, amount = 0.003, unit = 'ton kilometer', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        act = [act for act in eidb if 'market for waste plastic, mixture' == act['name'] and 'Europe' in act['location']][0]
        new_exc =  sintered_DW.new_exchange(input = act.key, amount = 0.045, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        sintered_DW.save()
        
        
    else:
        sintered_DW = [act for act in eidb if 'sintered diamond wire, steel' == act['name']][0]
    
    return sintered_DW
```

```{python}
sintered_DW = generate_DW_single_electroplated()
```

```{python}
sintered_DW = [act for act in eidb if 'sintered diamond wire, steel' in act['name']][0]
sintered_DW
```

### Wafer itself

```{python}
act = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' in act['name'] and 'RER' in act['location']][0]
act
```

```{python code_folding=c("0")}
wafer_original = [act for act in eidb
                      if 'multi-Si wafer production' == act['name'] 
                      and 'RER' in act['location']][0]
print_data(wafer_original)
```

```{python}
act = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' in act['name']][0]
act
```

```{python}
def ensure_wafer_dataset():
    
    
    wafer_original = [act for act in eidb
                      if 'multi-Si wafer production' == act['name'] 
                      and 'RER' in act['location']][0]
    wafer_adjusted = [act for act in eidb if 'multi-Si wafer production adjusted' == act['name']]
    
    if len(wafer_adjusted) == 0: 
        wafer_original = [act for act in eidb
                      if 'multi-Si wafer production' == act['name'] 
                      and 'RER' in act['location']][0]
        wafer_adjusted = wafer_original.copy()
        wafer_adjusted['name'] = 'multi-Si wafer production adjusted'
        wafer_adjusted['authors'] = 'Romain Besseau and Scarlett Tannous'
        wafer_adjusted['comment'] = 'Dataset adjusted with the adjustment of the amount of electricity, the corresponding dataset, the amount of Silicon and the corresponding Silicon solar grade dataset'      
        wafer_adjusted.save()
        
        
        
        silicon_adjusted = [act for act in eidb if
                            'silicon production, solar grade, modified Siemens process adjusted' 
                            in act['name'] and 'RER' in act['location']][0]
        new_exc = silicon_adjusted.new_exchange(input = silicon_adjusted.key,
                                                amount = 0.0, unit = 'kilogram',
                                                type = 'technosphere', 
                                                name = silicon_adjusted['name'])
        new_exc.save()
        silicon_adjusted.save()
                
               
        act = [act for act in eidb if 'sintered diamond wire, steel' in act['name'] and 'RER' in act['location']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 0, unit = 'meter', type = 'technosphere', name = act['name'])
        new_exc.save()
        wafer_adjusted.save()
        
        act = [act for act in eidb if 'silicon carbide, recycled production' in act['name']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 0, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        
        #Adjusting TEG recycled
        act = [act for act in eidb if 'triethylene glycol, recycled production' in act['name'] and 'RER' in act['location']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 0, unit = 'kilogram', type = 'technosphere', name = act['name'])
        new_exc.save()
        
        #Adding the 4 MJ natural gas used for the wafer as proposed by KBOB
        act = [act for act in eidb if 'at industrial furnace >100kW' in act['name'] and 'Europe' in act['location']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 4, unit = 'megajoule', type = 'technosphere', name = act['name'])
        new_exc.save()
        
        #adding the adjusted silicon
        act = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' in act['name']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 4, unit = 'megajoule', type = 'technosphere', name = act['name'])
        new_exc.save()
        
        #adding the adjusted silicon
        act = [act for act in eidb if 'silicon production, solar grade, modified Siemens process adjusted' in act['name']][0]
        new_exc = wafer_adjusted.new_exchange(input = act.key, amount = 0, unit = 'megajoule', type = 'technosphere', name = act['name'])
        new_exc.save()
        
        
        for exc in wafer_adjusted.exchanges():
            if exc['name'] == 'silicon, multi-Si, casted':
                silicon_amount = exc['amount']
                exc['amount'] = 0
                exc.save()
            if exc['name'] == 'silicon production, solar grade, modified Siemens process adjusted':
                exc['amount'] = silicon_amount
                exc.save()
                
        wafer_adjusted.save()  

            

    else:
        #wafer = [act for act in eidb if initial_dataset == act['name'] and 'RER' in act['location']][0]
        wafer_adjusted = [act for act in eidb if 'multi-Si wafer production adjusted' in act['name']][0]
        print(
            "By selecting the diamond wiring process: " 
            +"it is advised to consider 15% less silicon used (translated into 15% less kerf loss) "
            +"when compared to the traditional cutting process (44%)"
        )   
    #if DW false: DW = 1, if true DW = 0
    DW = 1
    for exc in wafer_adjusted.exchanges():
                    
            if exc['name'] == 'silicon carbide' :
                SiC_amount = exc['name']
                SiC_amount_adjusted = 2.02988
                exc['formula'] = 'DW*%f*(1.0 - SiC_recycled_share)'%(SiC_amount_adjusted,)
                #exc['amount'] = 0
                exc.save()
                
            if exc['name'] == 'triethylene glycol' :
                TEG_amount = exc['name']
                TEG_amount_adjusted = 2.16548
                exc['formula'] = 'DW*%f* (1.0 - TEG_recycled_share)'%(TEG_amount_adjusted,)
                #exc['amount'] = 0
                exc.save()
                
            if exc['name'] == 'silicon carbide, recycled production':
                exc['formula'] = 'DW * SiC_amount_adjusted* SiC_recycled_share'
                exc.save()
            
            if exc['name'] == 'triethylene glycol, recycled production':
                exc['formula'] = 'DW * TEG_amount_adjusted* TEG_recycled_share'
                exc.save()
       
            if exc['name'] == 'tap water' :
                tapwater_amount = exc['amount']
                exc['formula'] = '%f + (1.0-DW)*98.94'%(tapwater_amount)
                #exc['amount'] = exc['amount'] + 98.94
                exc.save()
                
            if exc['name'] == 'sintered diamond wire, steel' :
                exc['formula'] = '(1.0-DW)*0.0006075'
                #exc['amount'] = 0.0006075
                exc.save()

            if exc['name'] == 'electricity, medium voltage':
                exc['amount'] = 20  # It was 8 but it was modified by ST to 20
                elec_amount_wafer = exc['amount']
                exc['formula']= 'elec_amount_wafer * (1.0 - manufacturing_efficiency_gains)'
                exc.save()
            
            #Adjusting the amount of solar grade silicon used
            #Amount calculated from wafer thickness and Silicon density (2328 kg/m3)
            if exc['name'] == 'silicon production, solar grade, modified Siemens process adjusted':
                exc['formula'] = 'wafer_thickness*1e-06*2328 / (1-kerf_loss)'
                exc.save()
            #AskBenoit
            
            #Adjusting the electricity used for manufacturing
            if exc['name'] == 'electricity, medium voltage':
                    electricity_amount = exc
                    exc['formula'] = '%f * default_electricity_mix'%(electricity_amount['amount'])
                    exc.save()
                    
            wafer_adjusted.save()
        
    
    for x in electricity_activity_w_location:
        act = x['activity']
        exc = wafer_adjusted.new_exchange(
            input = act.key,
            name="%s %s"%(x['name'], x['location']),
            amount=0.0,
            unit=electricity_amount['unit'],
            category='',
            type=electricity_amount['type'],
            formula='%f * %s'%(electricity_amount['amount'], x['varname']))
        exc.save()
         
    wafer_adjusted.save()
    
    return wafer_adjusted
```

```{python}
wafer_adjusted = ensure_wafer_dataset()
wafer_adjusted
```

```{python}
print_data(wafer_adjusted)
```

```{python}
for exc in wafer_adjusted.exchanges():
    display(exc.as_dict())
```

```{python}

```
