[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lca_algebraic"
version = "1.4.1.dev0"

description = "This library provides a layer above Brightway for defining parametric models and running super fast LCA for monte carlo analysis."
readme = "README.md"
license = { text = "BSD" }
requires-python = ">=3.10,<3.14"

authors = [
  { name = "OIE - Mines ParisTech", email = "raphael.jolivet@mines-paristech.fr" }
]

keywords = ["LCA", "brightway2", "monte-carlo", "parametric"]

classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

dependencies = [
  "tabulate",
  "dill",
  "ipywidgets",
  "pandas<3.0.0",
  "pyarrow",
  "seaborn",
  "sympy",
  "matplotlib",
  "deprecation",
  "SALib",
  "pint",
  "typing-extensions",
]

[project.optional-dependencies]
bw2 = [
  "brightway2",
  "pypardiso; platform_machine == 'x86_64'",
]
bw25 = [
  "brightway25",
  "pypardiso; platform_machine == 'x86_64'",
]
dev = [
  "pre-commit",
  "pytest",
  "nbmake",
  "build"
]

[project.urls]
Homepage = "https://lca-algebraic.readthedocs.io/en/stable/"
Repository = "https://github.com/oie-mines-paristech/lca_algebraic.git"
Documentation = "https://lca-algebraic.readthedocs.io/"
Changelog = "https://github.com/oie-mines-paristech/lca_algebraic/blob/main/RELEASE_NOTES.md"

[tool.setuptools]
packages = ["lca_algebraic"]

[tool.setuptools.package-data]
lca_algebraic = ["README.md"]

[tool.pytest.ini_options]
norecursedirs = ["tmp"]

[tool.flake8]
max-line-length = 130
exclude = ["tests/*", "doc/*"]
ignore = ["E303", "E302", "W503", "E226", "W291"]
per-file-ignores = [
    "**/__init__.py:F403,F405,F401"
]

[tool.tox]
requires = ["tox>=4.31", "tox-uv>=1.25"]
env_list = [
    "py312-bw2",
    "py312-bw25",
    "py310-bw2",
    "py310-bw25",
    "py311-bw2",
    "py311-bw25",
    "py313-bw2",
    "py313-bw25",
]

[tool.tox.env_run_base]
package = "editable"
commands = [["pytest", "test"]]

[tool.tox.env."py310-bw2"]
base_python = "3.10"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway2",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py310-bw25"]
base_python = "3.10"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway25",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py311-bw2"]
base_python = "3.11"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway2",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py311-bw25"]
base_python = "3.11"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway25",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py312-bw2"]
base_python = "3.12"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway2",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py312-bw25"]
base_python = "3.12"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway25",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py313-bw2"]
base_python = "3.13"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway2",
    "pypardiso; platform_machine == 'x86_64'",
]

[tool.tox.env."py313-bw25"]
base_python = "3.13"
deps = [
    "pytest>=7",
    "nbmake",
    "brightway25",
    "pypardiso; platform_machine == 'x86_64'",
]

